# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BoAnd
email: mrboand@gmail.com
description: >
  Welcome to this web page.
baseurl: "" 
url: "https://boand.github.io" 
github_username:  boand
linkedin_username:  b0and


# Build settings
markdown: kramdown
